# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a603f0002ed280c1075729f9046f7abf35019a7c5cbdf585703724da94793516f03871f6fe3b185a1b716d04dadb89b9dd16157f60ee35ab880ee87cb3fd9ac

test:
  secret_key_base: 6ae75224f522ba6cdb93b2d8cdfe8f7ee1d952ea559079aea3ab39f689895ac943ff3d74d017cb9065b66a70d43148c7c0d2e09e591fd9ab69ece8d8e7c0bea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
